### ISSUE TITLE
should we allow signing formats other than JWS, ie LD-Proofs, JAdES and group signatures?

### ISSUE THREAD

**Issue by Sakurann** [oauthstuff/draft-selective-disclosure-jwt#12]
Do we want to allow signing formats other than JWS, ie LD-Proofs, JAdES and group signatures?

I am not an expert on JAdES, but from my understanding, I think it is close enough to JWS, it should be included. 
I do not see the benefit of including LD-Proofs and group signatures, since the whole point of this work was to enable selective disclosure without using those signature formats...

Based on the @alenhorvat 's comment to my PR: https://github.com/oauthstuff/draft-selective-disclosure-jwt/pull/1#discussion_r877144122

**Comment by danielfett** [comment]
Also, we need to keep things simple. JAdES can make sense.

**Comment by alenhorvat** [comment]
You're right. I missed one element:
- JWS, JAdES sign JSON as is
- LD-proofs, group signatures usually require additional transformation (and we're avoiding this).
Keeping JWS is sufficient. (JAdES results either with compact serialised or JSON serialised JWS, so we're covered).

Let's keep only JWS and we can close this issue.

**Comment by selfissued** [comment]
I agree that we should support only JWS signatures as JWTs do, since our spec is explicitly a JWT profile.

I think that we should close this issue with no action on that basis.

**Comment by Sakurann** [comment]
To clarify, do we agree that since signing as JWS allows for both JWS compact serialization and JWS JSON serialization, this specification supports JaDES?

**Comment by selfissued** [comment]
In the name of keeping simple things simple, I would advocate supporting exactly one signing format - the JWS Compact Serialization - making the same choice as JWTs.  That will result in the greatest interoperability.

If separately, we want to create a derived spec or specs saying how to use SD-JWTs, but with other signature types, we could do that.  But that should occur in separate specification(s) - not in the SD-JWT spec itself.

Also, note that many JWS implementations only support the Compact Serialization, because that's all you need for JWTs.  The JSON Serialization is more complicated in several aspects and is much more rarely implemented.  We should not take a dependence upon it.

**Comment by Sakurann** [comment]
Agreed to support only JWS Compact Serialization in SD-JWT and define a separate profile for JWS JSON serialization if needed.

@alenhorvat agrees.
