### ISSUE TITLE
allow unsigned SD-JWT?

### ISSUE THREAD

**Issue by Sakurann** [oauthstuff/draft-selective-disclosure-jwt#49]
describe why always sign if we are mandating to do so.

**Comment by PieterKas** [comment]
@Sakurann Proposed text for why the SD-JWT has to be signed (perhaps to be included in the security considerations?)

The SD-JWT is always signed by the issuer to prevent claims from being added or modified without being detected. The verifier must always check the signature to ensure that the SD-JWT has not been tampered with and that the claims included were not modified since the SD-JWT was signed by the issuer. If the signature on the SD-JWT cannot be verified the SD-JWT should be rejected. If the SD-JWT is not signed, an attacker may modify claims (e.g. change the "sub" attribute to identify another subject or "address" to modify a shipping address for goods ordered), thereby forging the issuer assertion. An attacker may also choose to add optional claims that the issuer had not asserted (e.g. adding an attribute indicating an academic qualification).

**Comment by Sakurann** [comment]
thanks Pieter, incorporated into the PR.

**Comment by danielfett** [comment]
Thanks for preparing the pull request. Approved and merged!
